feat: add getInstallation command
strmprivacy/cli pull request #86
Opened 2022-04-04 13:31 UTC by bobvandenhoogen

2022-04-07 07:32 UTC, jankeesvanandel requested changes

2022-04-07 07:32 UTC, jankeesvanandel commented on pkg/entity/installation/installation.go
> +	req := &installations.GetInstallationRequest{}
I thought we added an `installation_id` parameter to GetInstallation. Are the API definitions up to date?

2022-04-07 08:13 UTC, jankeesvanandel approved these changes

2022-04-07 08:15 UTC, jankeesvanandel commented
Looks good. I'm missing the ListInstallations operation, but maybe we don't yet need that one?

2022-04-08 08:05 UTC, trietsch approved these changes
LGTM

2022-04-08 08:05 UTC, merged

2022-04-08 08:06 UTC, strmprivacy-io commented
:tada: This PR is included in version 1.24.0 :tada:

The release is available on [GitHub release](https://github.com/strmprivacy/cli/releases/tag/v1.24.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: